#!/usr/bin/env python3
"""
flex_setup.py — One-shot setup + diagnostics for flex_radio_bot.py.

Run this once on your host machine to:
  1. Scan the LAN for the MHCOZY TYWB (auto-discover its IP).
  2. Verify Tuya credentials (device_id + local_key) work.
  3. Exercise the relay so you can confirm the wiring before you fly blind.
  4. Write the bot config to the platform-appropriate location:
       macOS : ~/.config/flexradio/flex_radio_bot.json
       Linux : /etc/meshcore/flex_radio_bot.json

Then re-run it any time you need to add an authorized operator, change the
pulse duration, or sanity-check the relay over the LAN.

Prereqs
-------
  macOS (Homebrew Python or system Python — use a venv):
    python3 -m venv .venv && source .venv/bin/activate
    pip install tinytuya

  Raspberry Pi / Debian Linux:
    sudo pip3 install tinytuya --break-system-packages
    (or use a venv — see macOS instructions above)

Getting the Tuya device_id + local_key
--------------------------------------
You need a (free) Tuya IoT developer account to extract the local_key. Easiest
path on a fresh setup:

  python3 -m tinytuya wizard

The wizard walks you through: create a "Cloud Project" at iot.tuya.com,
link your Smart Life account inside that project, paste the API key + secret +
region, and it writes out devices.json with all your local keys. Copy
device_id + local_key from there into this script (or let this script read
devices.json directly with --from-wizard).

Examples
--------
  # Full guided run (will use devices.json if present in cwd):
  sudo python3 flex_setup.py --from-wizard

  # Manual values:
  sudo python3 flex_setup.py \\
      --device-id bf1234567890abcdef \\
      --local-key XXXXXXXXXXXXXXXX \\
      --version 3.4 \\
      --add-key 7f3a...64hexchars... \\
      --add-key a91c...64hexchars...

  # Just test the relay (no config write):
  sudo python3 flex_setup.py --device-id ... --local-key ... --test-only
"""

from __future__ import annotations

import argparse
import getpass
import json
import platform
import sys
import time
from pathlib import Path

try:
    import tinytuya
except ImportError:
    sys.exit(
        "tinytuya not installed.\n"
        "  macOS : python3 -m venv .venv && source .venv/bin/activate && pip install tinytuya\n"
        "  Linux : sudo pip3 install tinytuya --break-system-packages"
    )

# Platform-aware default config path.
if platform.system() == "Darwin":
    DEFAULT_CONFIG_PATH = Path.home() / ".config" / "flexradio" / "flex_radio_bot.json"
else:
    DEFAULT_CONFIG_PATH = Path("/etc/meshcore/flex_radio_bot.json")


def scan_lan() -> dict:
    """
    Perform a local area network broadcast scan to discover active Tuya devices.

    This function leverages TinyTuya's device discovery capabilities to broadcast UDP packets and
    listens for 15 seconds to collect responses from active devices on the local Wi-Fi subnet.

    Returns:
        dict: A dictionary mapping discovered device IP addresses to their metadata (e.g., ID, version).
    """
    print("Scanning LAN for Tuya devices (15s)...")
    devices = tinytuya.deviceScan(False, 15)
    if not devices:
        print("  No Tuya devices answered. Check the TYWB is powered and on the same Wi-Fi.")
        return {}
    for ip, info in devices.items():
        print(f"  found {ip}  id={info.get('gwId')}  version={info.get('version')}")
    return devices


def load_from_wizard(device_id: str | None) -> tuple[str, str, float, str]:
    """
    Retrieve Tuya credentials and connection details from a local `devices.json` file.

    `devices.json` is typically generated by running `python3 -m tinytuya wizard`.
    This function reads the file and looks for a match on the specified device ID.
    If no device ID is provided and the file contains exactly one device, it automatically
    selects that device.

    Args:
        device_id (str | None): The specific Tuya device ID to filter by, or None.

    Returns:
        tuple[str, str, float, str]: A tuple containing (device_id, local_key, protocol_version, ip_address).

    Raises:
        SystemExit: If `devices.json` is missing, contains multiple devices (and none is selected),
                    or the specified device ID is not found.
    """
    path = Path("devices.json")
    if not path.exists():
        sys.exit("devices.json not found. Run `python3 -m tinytuya wizard` first.")
    with path.open() as fh:
        entries = json.load(fh)

    if device_id:
        match = [e for e in entries if e.get("id") == device_id]
    elif len(entries) == 1:
        match = entries
    else:
        print("Multiple devices in devices.json — pick one with --device-id:")
        for e in entries:
            print(f"  {e.get('id')}  name={e.get('name')}")
        sys.exit(1)

    if not match:
        sys.exit(f"device_id {device_id!r} not in devices.json")

    e = match[0]
    return e["id"], e["key"], float(e.get("ver", 3.4)), e.get("ip", "Auto")


def fetch_vault_secret(url: str, secret_path: str, secret_key: str, token: str | None, token_path: str | None) -> str:
    """
    Retrieve the local key from a HashiCorp Vault server.

    Args:
        url (str): Vault server URL.
        secret_path (str): API endpoint path.
        secret_key (str): Dictionary key to lookup.
        token (str | None): Plaintext token.
        token_path (str | None): Token file path.

    Returns:
        str: The retrieved secret value.
    """
    import json
    import os
    import urllib.error
    import urllib.request
    from pathlib import Path

    if not token and token_path:
        try:
            token = Path(token_path).read_text().strip()
        except OSError as e:
            sys.exit(f"Error reading Vault token from {token_path}: {e}")

    if not token:
        token = os.environ.get("VAULT_TOKEN")

    if not token:
        sys.exit("Error: --use-vault requires a Vault token (passed via --vault-token, --vault-token-path, or the VAULT_TOKEN environment variable).")

    base_url = url.rstrip("/")
    path = secret_path.lstrip("/")
    full_url = f"{base_url}/{path}"

    print(f"Fetching key from Vault at {full_url}...")
    req = urllib.request.Request(full_url)
    req.add_header("X-Vault-Token", token)
    req.add_header("Accept", "application/json")

    try:
        with urllib.request.urlopen(req, timeout=5.0) as response:
            res_data = json.loads(response.read().decode("utf-8"))
    except Exception as e:
        sys.exit(f"Error fetching from Vault: {e}")

    try:
        data = res_data.get("data", {})
        if "data" in data and isinstance(data["data"], dict):
            # KV V2
            secret_value = data["data"].get(secret_key)
        else:
            # KV V1
            secret_value = data.get(secret_key)

        if not secret_value:
            sys.exit(f"Error: Secret key {secret_key!r} not found in Vault response.")

        return str(secret_value)
    except Exception as e:
        sys.exit(f"Error parsing Vault response: {e}")


def connect(device_id: str, local_key: str, address: str, version: float):
    """
    Establish a connection client instance with the local Tuya relay device.

    Args:
        device_id (str): The unique identifier of the Tuya device.
        local_key (str): The local cryptographic key required to authenticate with the device.
        address (str): The IP address of the device, or 'Auto' to discover it via UDP broadcast.
        version (float): The Tuya protocol version (typically 3.1 to 3.5).

    Returns:
        tinytuya.OutletDevice: An OutletDevice helper object ready to communicate with the physical relay.
    """
    return tinytuya.OutletDevice(
        dev_id=device_id,
        address=address,
        local_key=local_key,
        version=version,
        connection_timeout=4,
    )


def exercise_relay(d, channel: int) -> None:
    """
    Interactively test and verify the relay's physical actuation over the network.

    This function first queries the current status of the Tuya relay. If successful,
    it executes a brief 500ms momentary closed-pulse (short-press) and prompts the operator
    to confirm if the radio responded. It then offers an option to perform a 5-second
    closed-pulse (long-press) to test the hard power-off safety fallback.

    Args:
        d (tinytuya.OutletDevice): The connected Tuya OutletDevice instance.
        channel (int): The target relay channel to actuate (1-4).

    Raises:
        SystemExit: If the device fails to return status/DPS, indicating authentication
                    or network connectivity issues.
    """
    print(f"\nExercising channel {channel}. Listen for the click and watch the radio.")
    print("  reading current state...")
    s = d.status()
    print(f"  status: {s}")
    if not isinstance(s, dict) or "dps" not in s:
        sys.exit("  device did not return dps. Wrong key, version, or IP?")

    print("  closing relay (500ms pulse) — this is what '!flex on' will send...")
    d.set_status(True, switch=channel)
    time.sleep(0.5)
    d.set_status(False, switch=channel)

    input("  did the radio respond to a short-press? (press Enter to continue) ")

    if input("  send a long-press (5s) to verify hard power-off? [y/N] ").lower().startswith("y"):
        d.set_status(True, switch=channel)
        time.sleep(5.0)
        d.set_status(False, switch=channel)
        print("  long-press done.")


def write_config(path: Path, cfg: dict) -> None:
    """
    Atomically write the normalized bot configuration to disk with secure permissions.

    To avoid partial writes or corruption, this function writes the JSON config to a
    temporary file, sets its permissions securely to 0600 (read/write only by the owner),
    and then replaces the destination file atomically.

    Args:
        path (Path): The target file path to write to (typically `/etc/meshcore/flex_radio_bot.json`).
        cfg (dict): The configuration dictionary to serialize.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".json.tmp")
    with tmp.open("w") as fh:
        json.dump(cfg, fh, indent=2, sort_keys=True)
    tmp.chmod(0o600)
    tmp.replace(path)
    restart_hint = (
        "launchctl stop com.meshcore.remote-terminal && launchctl start com.meshcore.remote-terminal"
        if platform.system() == "Darwin"
        else "sudo systemctl restart remote-terminal"
    )
    print(f"\nWrote {path} (mode 600).")
    print(f"Restart Remote-Terminal-for-MeshCore to pick up the new config:")
    print(f"  {restart_hint}")


def main() -> int:
    """
    Command-line interface entry point for setting up and testing the FlexRadio power bot.

    This function parses CLI arguments, runs subnet scans, extracts wizard credentials,
    interactively exercises the hardware, validates MeshCore operator public keys,
    writes the finalized configuration to disk, and configures secure logging permissions.

    Returns:
        int: Exit status code (0 for success, non-zero for failure).
    """
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--device-id", help="Tuya device ID")
    ap.add_argument("--local-key", help="Tuya local key (omit to be prompted)")
    ap.add_argument("--address", default="Auto", help="device IP, or 'Auto' to discover")
    ap.add_argument("--version", type=float, default=3.4, help="Tuya protocol version (3.1-3.5)")
    ap.add_argument("--channel", type=int, default=1, help="relay channel (1-4)")
    ap.add_argument("--from-wizard", action="store_true", help="read creds from devices.json")
    ap.add_argument("--add-key", action="append", default=[],
                    help="64-hex MeshCore public key to allowlist (repeatable)")
    ap.add_argument("--flex-host", default=None, help="hostname/IP of Flex for status pings")
    ap.add_argument("--allow-channel-control", action="store_true",
                    help="allow !flex on/off in channel (NOT RECOMMENDED)")
    ap.add_argument("--config", default=str(DEFAULT_CONFIG_PATH))
    ap.add_argument("--scan-only", action="store_true", help="just scan and exit")
    ap.add_argument("--test-only", action="store_true", help="exercise relay, don't write config")
    ap.add_argument("--use-vault", action="store_true", help="use HashiCorp Vault for local_key")
    ap.add_argument("--vault-url", default="http://127.0.0.1:8200", help="Vault server URL")
    ap.add_argument("--vault-token", default=None, help="Vault API token")
    ap.add_argument("--vault-token-path", default=None, help="Vault API token file path")
    ap.add_argument("--vault-secret-path", default="v1/secret/data/flexradio", help="Vault secret path")
    ap.add_argument("--vault-secret-key", default="tuya_local_key", help="Vault secret key name")
    args = ap.parse_args()

    if args.scan_only:
        scan_lan()
        return 0

    if args.use_vault:
        if args.from_wizard:
            sys.exit("Error: Cannot use --from-wizard and --use-vault simultaneously.")
        device_id = args.device_id or input("device_id: ").strip()
        local_key = fetch_vault_secret(
            args.vault_url,
            args.vault_secret_path,
            args.vault_secret_key,
            args.vault_token,
            args.vault_token_path,
        )
        version = args.version
        address = args.address
    elif args.from_wizard:
        device_id, local_key, version, address = load_from_wizard(args.device_id)
    else:
        device_id = args.device_id or input("device_id: ").strip()
        local_key = args.local_key or getpass.getpass("local_key: ").strip()
        version = args.version
        address = args.address

    if not device_id or not local_key:
        sys.exit("device_id and local_key are required")

    print(f"\nConnecting to {device_id} at {address} v{version}...")
    d = connect(device_id, local_key, address, version)
    exercise_relay(d, args.channel)

    if args.test_only:
        return 0

    # Validate allowlist entries look like 64-hex.
    for k in args.add_key:
        if len(k) != 64 or any(c not in "0123456789abcdefABCDEF" for c in k):
            sys.exit(f"--add-key {k!r} is not 64-hex")

    cfg = {
        "tuya_device_id": device_id,
        "tuya_local_key": "" if args.use_vault else local_key,
        "tuya_address": address,
        "tuya_version": version,
        "relay_channel": args.channel,
        "short_pulse_seconds": 0.5,
        "long_pulse_seconds": 5.0,
        "cooldown_seconds": 3.0,
        "allowed_sender_keys": [k.lower() for k in args.add_key],
        "flex_host": args.flex_host,
        "flex_smartsdr_port": 4992,
        "log_path": str(
            Path.home() / "Library" / "Logs" / "flex_radio_bot.log"
            if platform.system() == "Darwin"
            else Path("/var/log/flex_radio_bot.log")
        ),
        "allow_channel_control": bool(args.allow_channel_control),
        "use_vault": bool(args.use_vault),
        "vault_url": args.vault_url,
        "vault_token": args.vault_token,
        "vault_token_path": args.vault_token_path,
        "vault_secret_path": args.vault_secret_path,
        "vault_secret_key": args.vault_secret_key,
    }
    write_config(Path(args.config), cfg)

    # Make sure the log file is writable by whoever runs Remote-Terminal.
    try:
        Path(cfg["log_path"]).touch(exist_ok=True)
        Path(cfg["log_path"]).chmod(0o640)
    except OSError as e:
        print(f"  (couldn't pre-create {cfg['log_path']}: {e}; the bot will fall back to stderr)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
